#!/bin/zsh
#
#   This file is part of Dash Ninja.
#   https://github.com/elbereth/dashninja-ctl
#
#   Dash Ninja is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Dash Ninja is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Dash Ninja.  If not, see <http://www.gnu.org/licenses/>.
#

# Disable logging by default
updatelog=/dev/null
statuslog=/dev/null
votesrrdlog=/dev/null
balancelog=/dev/null
portchecklog=/dev/null
autoupdatelog=/dev/null

# If parameter 1 is log then enable logging
if [[ "$1" == "log" ]]; then
  updatelog=log/update.log
  statuslog=log/status.log
  votesrrdlog=log/votesrrd.log
  balancelog=log/balance.log
  portchecklog=log/portcheck.log
  autoupdatelog=log/autoupdate.log
fi

# Sequentially run scripts
#/mnt/d/Nginx/www/aither-ninja-ctl/aitherdupdate >> $updatelog
/mnt/d/Nginx/www/aither-ninja-ctl/dmnctl status >> $statuslog
#/mnt/d/Nginx/www/aither-ninja-ctl/dmnvotesrrd >> $votesrrdlog
/usr/bin/php /mnt/d/Nginx/www/aither-ninja-ctl/dmndbgen masternodeactive >> $statuslog
/usr/bin/php /mnt/d/Nginx/www/aither-ninja-fe/api/cron.php main nodesstatus >> $statuslog
/usr/bin/php /mnt/d/Nginx/www/aither-ninja-fe/api/cron.php main blocksconsensus >> $statuslog
/usr/bin/php /mnt/d/Nginx/www/aither-ninja-fe/api/cron.php main votelimit >> $statuslog
/usr/bin/php /mnt/d/Nginx/www/aither-ninja-fe/api/cron.php main masternodeslistfull >> $statuslog
/usr/bin/php /mnt/d/Nginx/www/aither-ninja-fe/api/cron.php main governanceproposals >> $statuslog
/usr/bin/php /mnt/d/Nginx/www/aither-ninja-fe/api/cron.php main governancetriggers >> $statuslog

# Concurrently run scripts
/usr/bin/nice -n 18 /mnt/d/Nginx/www/aither-ninja-ctl/dmnbalance >> $balancelog &
/usr/bin/nice -n 19 /mnt/d/Nginx/www/aither-ninja-ctl/dmnportcheck db >> $portchecklog &
/usr/bin/nice -n 15 /mnt/d/Nginx/www/aither-ninja-ctl/dmnautoupdate >> $autoupdatelog &
